In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Advertising.csv")
df

TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [3]:
X = df.drop("sales",axis=1)
y = df["sales"]

# Polynomial Conversion

In [4]:
from sklearn.preprocessing import PolynomialFeatures

In [5]:
polynomial_conversion = PolynomialFeatures(degree=3, include_bias=False)

In [6]:
poly_features = polynomial_conversion.fit_transform(X)
poly_features

array([[2.30100000e+02, 3.78000000e+01, 6.92000000e+01, ...,
        9.88757280e+04, 1.81010592e+05, 3.31373888e+05],
       [4.45000000e+01, 3.93000000e+01, 4.51000000e+01, ...,
        6.96564990e+04, 7.99365930e+04, 9.17338510e+04],
       [1.72000000e+01, 4.59000000e+01, 6.93000000e+01, ...,
        1.46001933e+05, 2.20434291e+05, 3.32812557e+05],
       ...,
       [1.77000000e+02, 9.30000000e+00, 6.40000000e+00, ...,
        5.53536000e+02, 3.80928000e+02, 2.62144000e+02],
       [2.83600000e+02, 4.20000000e+01, 6.62000000e+01, ...,
        1.16776800e+05, 1.84062480e+05, 2.90117528e+05],
       [2.32100000e+02, 8.60000000e+00, 8.70000000e+00, ...,
        6.43452000e+02, 6.50934000e+02, 6.58503000e+02]])

# Train and Test split

In [69]:
from sklearn.model_selection import train_test_split

In [70]:
X_train,X_test,y_train,y_test = train_test_split(poly_features,
                                                 y,
                                                 test_size= .3,
                                                 random_state=101)

# Scaling the Data

StandardScalar = Z-score

In [71]:
from sklearn.preprocessing import StandardScaler

In [72]:
#help (standardscalar)

In [73]:
scaler = StandardScaler()

In [74]:
scaler.fit(X_train)

StandardScaler()

In [75]:
X_test = scaler.transform(X_test)

In [127]:
X_train = scaler.transform(X_test)

In [128]:
X_train[0]

array([-1.81079901, -1.4683538 , -1.42107822, -1.18338519, -1.10029124,
       -0.95155786, -1.05506139, -0.89977401, -0.79587121, -0.9339174 ,
       -0.85411893, -0.72397979, -0.82050449, -0.6910803 , -0.58978893,
       -0.84796655, -0.72629643, -0.61592631, -0.54660144])

In [129]:
poly_features[0]

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

# Ridge Regression

In [130]:
from sklearn.linear_model import Ridge

In [131]:
ridge_model = Ridge(alpha = 10)

In [132]:
ridge_model.fit(X_train,y_train)

ValueError: Found input variables with inconsistent numbers of samples: [60, 140]

In [81]:
test_predictions = ridge_model.predict(X_test)
test_predictions

array([4.21457707, 4.33136847, 4.18666321, 4.25114534, 4.09688619,
       4.07944799, 4.34862793, 4.28843856, 4.16539175, 4.32750899,
       4.13914991, 4.2253771 , 4.25342932, 4.35088348, 4.32725687,
       4.12350692, 4.29785561, 4.11851408, 4.09944352, 4.34066352,
       4.08464797, 4.2901456 , 4.41863993, 4.39816747, 4.10405324,
       4.242104  , 4.36964852, 4.12428587, 4.21264984, 4.1635289 ,
       4.1475145 , 4.33166669, 4.1657809 , 4.08897943, 4.28410391,
       4.13295823, 4.14185149, 4.12463608, 4.12592125, 4.18288354,
       4.2251726 , 4.1748724 , 4.16461487, 4.10673467, 4.15860894,
       4.13669494, 4.08458781, 4.30541516, 4.25299996, 4.33963795,
       4.16406555, 4.2559072 , 4.33045859, 4.16638477, 4.23352556,
       4.04554935, 4.37645814, 4.13851357, 4.32463494, 4.25597038])

In [82]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [83]:
MAE = mean_absolute_error(y_test, test_predictions)
MSE = mean_squared_error(y_test, test_predictions)
RMSE = np.sqrt(MSE)

In [84]:
MAE

9.160833136208556

In [85]:
MSE

110.69081691311618

In [86]:
RMSE

10.520970340853365

In [87]:
# Training the set performance

train_predictions = ridge_model.predict(X_train)
train_predictions

array([15.04700258, 25.94920805,  8.75542774, 21.28579581, 11.94767647,
       21.84534003, 15.56386762, 14.51693986, 16.17943822, 17.8219851 ,
       11.95359901,  9.56180601, 16.07263298,  8.73838718, 10.4612026 ,
       21.89683624, 13.82730497, 25.45829859,  6.3874366 , 13.23586255,
       16.32346422, 13.40252479,  8.63376072, 22.38954027, 19.68914724,
       15.73442553,  6.28293265, 11.91827981, 20.64717546, 12.59856538,
        6.81685434, 12.34151737, 11.05355267, 10.60889954, 11.4215889 ,
       15.30960399, 10.60496632, 14.62019362, 13.66236047, 11.24721774,
       12.8870745 , 25.90546009, 11.0107529 , 10.23222137, 15.50520508,
       18.6547848 ,  5.64617645, 16.3557094 , 24.09528972, 12.06776434,
       12.78768591, 11.05102259, 10.86835867, 19.86433475, 17.47989955,
       22.588444  , 18.99666975, 12.42997794, 22.1516751 , 12.13508892,
       18.5602929 , 14.48042806, 13.14819471, 11.77544012, 15.99306503,
       21.11088045, 15.7837532 , 25.40660817, 19.63748381, 23.94

In [88]:
# CHECK

MAE = mean_absolute_error(y_train, train_predictions)
MAE

0.2911258978819365

# Lasso Regression

In [89]:
from sklearn.linear_model import LassoCV

In [133]:
lasso_cv_model = LassoCV(eps = 0.1, n_alphas = 10, cv = 5)

In [91]:
lasso_cv_model.fit(X_train, y_train)

LassoCV(cv=5, eps=0.1)

In [92]:
test_prediction = lasso_cv_model.predict(X_test)

In [93]:
MAE = mean_absolute_error(y_test, test_prediction)
MSE = mean_squared_error(y_test, test_prediction)
RMSE = np.sqrt(MSE)

In [94]:
MAE

4.079033417539845

In [95]:
MSE

31.72660710809843

In [96]:
RMSE

5.632637668810096

In [97]:
lasso_cv_model.coef_

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 4.26656276e-07, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00])

# Elastic Net

In [98]:
from sklearn.linear_model import ElasticNetCV

In [117]:
elastic_model = ElasticNetCV(l1_ratio = [.1, .5, .7, .9, .95, .99, .1], 
                             eps = .1,
                             n_alphas = 100)

In [118]:
elastic_model.fit(X_train, y_train)

ElasticNetCV(eps=0.1, l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 0.1])

In [119]:
elastic_model.l1_ratio

[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 0.1]

In [120]:
test_predictions = elastic_model.predict(X_test)

In [121]:
MAE = mean_absolute_error(y_test, test_prediction)
MSE = mean_squared_error(y_test, test_prediction)
RMSE = np.sqrt(MSE)

In [122]:
MAE

4.079033417539845

In [123]:
MSE

31.72660710809843

In [124]:
RMSE

5.632637668810096

In [125]:
# TRAIN SET PERFORMANCE

train_predictions = elastic_model.predict(X_train)
MAE = mean_absolute_error(y_train,train_predictions)

In [126]:
MAE

3.1944913892321694