# Concept Session - Ridge and Lasso Regression

## Demo 1: Ridge Regression

### Import the standard libraries numpy and (parts of) sklearn

In [1]:
# the following code snippet are taken from 
# https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Ridge.html#sklearn.linear_model.Ridge
# and
# https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Lasso.html#sklearn.linear_model.Lasso

The history saving thread hit an unexpected error (DatabaseError('database disk image is malformed')).History will not be written to the database.


In [1]:
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
import numpy as np

from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

### Generating a toy data set

In [2]:
# in this example we re-use the very simple toy dataset from the DS2.2 notebook

In [3]:
# we set some x-values

In [57]:
X = np.array([[1, 10], [1, 20], [2, 20], [2, 30], [5, 40], [-2, 30]])

In [58]:
# and construct corresponding y-values

In [59]:
# y = 4 * x_0 + 2 * x_1 + 13

y = np.dot(X, np.array([4, 2])) + 13

# add some random noise to the y-values

y = y + 50*np.random.randn(len(y))
y

array([ 58.5676495 , 125.30956753,  71.53436764,  68.85990385,
       159.27704922,  71.42622768])

In [60]:
# i.e. we are mapping 2D input values onto 1D target values

### Training the model

In [61]:
# we use the class sklearn.linear_model.Ridge in the following. 
# Before we actually fit a linear model to data, we have to 'configure' the linear model.

In [62]:
# We determine whether to use an intercept: "fit_intercept = True / False", default value is "True"

In [63]:
# and we determine whether to use normalized attributes: "normalize = True / False", default value is "False"

In [64]:
# in contrast to ordinary linear regression, we moreover need to set the regularization strength alpha.

In [65]:
# For the moment, we simply choose alpha = 1

In [66]:
# Now, we create a "Ridge" object and fit it into the toy dataset

In [67]:
reg = Ridge(alpha=1).fit(X, y)

### Evaluating the model

In [68]:
# various scores for evaluation: root-mean-square error (RMSE), mean absolute error (MAE), R^2 score

In [69]:
# first, we evaluate the R^2 score (on training data, to check the quality of the fit)

In [70]:
reg.score(X, y)

0.5303506546445942

In [71]:
# We reach a value of approx. 0.85. We do not reach an ideal value of 1.0 as we added random noise that cannot be predicted.

In [72]:
mean_squared_error(y, reg.predict(X))

636.3405859445098

In [73]:
mean_absolute_error(y, reg.predict(X))

19.857014371637963

In [74]:
# Let's have a look at the learned model parameters:

In [75]:
reg.coef_

array([8.12526687, 1.56481845])

In [76]:
# Above we decided that the linear model should have a learnable intercept. 
# Let's have a look at which value it takes on:

In [77]:
reg.intercept_

41.18743257496658

### Inference

In [78]:
# Having optimized the model, we can now predict y-values for previously unseen input values x.

In [79]:
# Let's check the following two datapoints:

In [80]:
xnew1 = [3,5]

In [81]:
xnew2 = [-23,9]

In [82]:
# The can evaluate several input values at a time by passing them as array elements

In [83]:
reg.predict(np.array([xnew1, xnew2]))

array([  73.38732547, -131.61033945])

### Impact of the Regularization Strength

In [84]:
reg = Ridge(alpha=0.1).fit(X, y)
reg.score(X, y)

0.5307078609708475

In [85]:
# the differences between alpha = 1 and alpha = 0.1 are rather small

In [86]:
reg = Ridge(alpha=100).fit(X, y)
reg.score(X, y)

0.39767053163276367

In [87]:
# for alpha = 100, the model is underfitting as can be seen by the significantly smaller R^2 value

## Demo 2: Lasso Regression

In [88]:
# For Lasso regression, we re-use the (linear and noisy) toy dataset from above.

In [89]:
# We set the regularization strength alpha = 0.1 and fit it to the data.

In [90]:
from sklearn import linear_model
reg = Lasso(alpha=0.1).fit(X,y)

print(reg.score(X,y))

0.5307099877934491


In [1]:
# It yields an R^2 score comparable to ridge regression.